### ISSUE TITLE
Support block or list of functions to forward for improved readability

### ISSUE THREAD

**Issue by serenity4** [curtd/ForwardMethods.jl#15]
Hi,

I wondered if we could improve the API in the case where we have many methods to forward. For example:
```julia
@forward_methods LayoutEngine field = :storage object_type position_type coordinate_type geometry_type get_position set_position! get_geometry(_, object) set_geometry!() coordinates(_, x) get_coordinates(_, object) set_coordinates(_, position, coords) get_position(_, object) set_position!(_, object, position)
```

I was thinking we could support block (or vector) expressions, such as
```julia
@forward_methods LayoutEngine field = :storage begin
  object_type
  position_type
  coordinate_type
  geometry_type
  get_position
  set_position!
  get_geometry(_, object)
  set_geometry!()
  coordinates(_, x)
  get_coordinates(_, object)
  set_coordinates(_, position, coords)
  get_position(_, object)
  set_position!(_, object, position)
end
```

(`begin ... end` could also be replaced by `[...]`)

Implementation-wise, `@forward_methods` would have an additional method for a single `args::Expr`, so users can use the existing (inline) or new (block/vector) syntax depending on what they prefer/is more readable for a given list of methods.

What do you think ?

**Comment by curtd** [comment]
Good idea! Turns out the block idea was really quick to implement, so I just opted for that.

**Comment by serenity4** [comment]
Awesome, thanks!
